import Image from "next/image";
import styles from "./page.module.css";
import Head from "next/head";
import Script from "next/script";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="nextjs, huntingcoder blog, hunting coder"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blogs</li>
          <li>Contact</li>
          </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>

        <p className={styles.description}>
          A blog for hunting coder by the hunting coder ⚔
        </p>

        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogitem}>
            <h3>How to Learn javascript ?</h3>
            <p>
              Javascript is the language used to design the logic for the web.
            </p>
          </div>
          <div className={styles.blogitem}>
            <h3>How to Learn javascript ?</h3>
            <p>
              Javascript is the language used to design the logic for the web.
            </p>
          </div>
          <div className={styles.blogitem}>
            <h3>How to Learn javascript ?</h3>
            <p>
              Javascript is the language used to design the logic for the web.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
