"use client"

import Image from "next/image";
import styles from "./page.module.css";
import Head from "next/head";


export default function Home() {
  return (
    <div className={styles.container}>
      {" "}
      <style jsx>{`
        h2 {
          font-size: 28px;
        }
      `}</style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="nextjs, huntingcoder blog, hunting coder"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
  
      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>
        <div className={styles.imgWrap}>
          <Image
            src="/coder.jpg"
            alt="Picture of the coder"
            objectFit="cover"
            width={260}
            height={170}
            style={{
              borderRadius: "10px",
              boxShadow: "0 4px 8px rgba(36, 217, 103, 0.1)",
              border: "4px solid white",
            }}
          />
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder ⚔
        </p>

        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogitem}>
            <h3>How to Learn javascript ?</h3>
            <p>
              Javascript is the language used to design the logic for the web.
            </p>
          </div>
          <div className={styles.blogitem}>
            <h3>How to Learn javascript ?</h3>
            <p>
              Javascript is the language used to design the logic for the web.
            </p>
          </div>
          <div className={styles.blogitem}>
            <h3>How to Learn javascript ?</h3>
            <p>
              Javascript is the language used to design the logic for the web.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
